# Generated by Django 3.2.7 on 2021-09-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surename', models.CharField(max_length=250)),
                ('fathername', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('birthday', models.DateField()),
            ],
            options={
                'verbose_name': 'Authors',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('write_date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/%y/%m/%d')),
                ('author_relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.authors', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publishings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Publishings',
                'verbose_name_plural': 'Publishings',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of shop')),
                ('adress', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=16)),
                ('assortiment', models.ManyToManyField(blank=True, null=True, related_name='Assortiment_of_books', to='books.Books')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=250)),
                ('review', models.CharField(max_length=3000)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.books', verbose_name='book')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review',
                'ordering': ['nickname'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='publishing_relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publishings', verbose_name='publishing'),
        ),
    ]
