# Generated by Django 3.2.7 on 2021-10-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='adress',
            new_name='address',
        ),
    ]
