# Generated by Django 3.2.7 on 2021-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_adress_shop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_books', models.IntegerField(verbose_name='Count of books')),
                ('save_date', models.DateField(auto_now_add=True, verbose_name='Date save of stats')),
                ('save_books_name', models.CharField(max_length=1500, verbose_name='List of books for day')),
            ],
            options={
                'verbose_name': 'Statistic for day',
                'verbose_name_plural': 'Statistic for day',
            },
        ),
    ]
