# Generated by Django 3.2.7 on 2021-11-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_statdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statdata',
            name='save_books_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='List of books for day'),
        ),
    ]
